name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  # Unit Tests
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Frontend Unit Tests
      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend unit tests and collect coverage
        working-directory: ./frontend
        run: npm run test:ci:unit

      # Save frontend unit test report
      - name: Upload frontend unit test report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-unit-test-report
          path: ./frontend/coverage/lcov-report/**

      # Backend Unit Tests
      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm ci

      - name: Run backend unit tests and collect coverage
        working-directory: ./backend
        run: npm run test:ci:unit

      # Save backend unit test report
      - name: Upload backend unit test report
        uses: actions/upload-artifact@v3
        with:
          name: backend-unit-test-report
          path: ./backend/coverage/lcov-report/**

  # Integration Tests
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: [unit-tests]
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Frontend Integration Tests
      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend integration tests and collect coverage
        working-directory: ./frontend
        run: npm run test:ci:integration -- --passWithNoTests

      # Save frontend integration test report
      - name: Upload frontend integration test report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-integration-test-report
          path: ./frontend/coverage/lcov-report/**

      # Backend Integration Tests
      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm ci

      - name: Run backend integration tests and collect coverage
        working-directory: ./backend
        run: npm run test:ci:integration

      # Save backend integration test report
      - name: Upload backend integration test report
        uses: actions/upload-artifact@v3
        with:
          name: backend-integration-test-report
          path: ./backend/coverage/lcov-report/**

  # E2E Tests
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: [integration-tests]
    timeout-minutes: 60
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests and generate HTML report
        run: npx playwright test --reporter=html

      - name: List Playwright report files
        run: ls -lR playwright-report

      # Upload Playwright report as artifact
      - name: Upload Playwright report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ./frontend/playwright-report/


  # Deploy Test Reports to GitHub Pages
  deploy-reports:
    name: Deploy Test Reports
    needs: [unit-tests, integration-tests, e2e-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0
          clean: false

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Copy navbar.html and custom.css
      - name: Copy navbar and CSS files
        run: |
          git checkout origin/develop -- workflow_templates/navbar.html workflow_templates/custom.css
          cp workflow_templates/navbar.html ./
          cp workflow_templates/custom.css ./

      # Download artifacts
      - name: Download Playwright report
        uses: actions/download-artifact@v3
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/

      - name: Download frontend unit test report
        uses: actions/download-artifact@v3
        with:
          name: frontend-unit-test-report
          path: unit-tests/frontend

      - name: Download backend unit test report
        uses: actions/download-artifact@v3
        with:
          name: backend-unit-test-report
          path: unit-tests/backend

      - name: Download frontend integration test report
        uses: actions/download-artifact@v3
        with:
          name: frontend-integration-test-report
          path: integration-tests/frontend

      - name: Download backend integration test report
        uses: actions/download-artifact@v3
        with:
          name: backend-integration-test-report
          path: integration-tests/backend

      # List downloaded artifacts to verify
      - name: List downloaded artifacts
        run: |
          ls -lR e2e-tests/playwright-report/
          ls -lR unit-tests/
          ls -lR integration-tests/

      # Organize Test Reports
      - name: Organize Test Reports
        run: |
          mkdir -p reports/frontend/unit-tests
          mkdir -p reports/frontend/integration-tests
          mkdir -p reports/backend/unit-tests
          mkdir -p reports/backend/integration-tests
          mkdir -p reports/e2e-tests

          # Move the reports
          mv unit-tests/frontend/* reports/frontend/unit-tests/
          mv integration-tests/frontend/* reports/frontend/integration-tests/
          mv unit-tests/backend/* reports/backend/unit-tests/
          mv integration-tests/backend/* reports/backend/integration-tests/
          mv e2e-tests/playwright-report/* reports/e2e-tests/

      # Inject Navbar and Custom CSS
      - name: Inject Navbar and Custom CSS into Reports
        run: |
          # Copy custom.css into the reports directory
          cp custom.css reports/

          # Inject navbar and custom CSS into all HTML files
          find reports/ -name '*.html' | while read html_file; do
            # Insert the custom CSS link after the <head> tag
            sed -i '/<head>/a <link rel="stylesheet" href="/reports/custom.css">' "$html_file"
            # Insert the navbar after the <body> tag
            sed -i '/<body>/a <!-- Navbar Start -->' "$html_file"
            sed -i '/<!-- Navbar Start -->/r navbar.html' "$html_file"
            sed -i '/<!-- Navbar Start -->/d' "$html_file"
          done

      # List reports directory to verify
      - name: List reports directory to verify
        run: ls -lR reports/

      # Generate index.html
      - name: Generate index.html
        run: |
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>Test Reports</title>
            <link rel="stylesheet" href="/reports/custom.css">
          </head>
          <body>
            <!-- Navbar will be inserted here -->
          </body>
          </html>
          EOF

          # Insert the navbar
          sed -i '/<!-- Navbar will be inserted here -->/r navbar.html' index.html
          sed -i '/<!-- Navbar will be inserted here -->/d' index.html

          # Add content to index.html
          cat <<EOF >> index.html
          <h1>Test Reports</h1>
          <ul>
            <li><a href="reports/frontend/unit-tests/index.html">Frontend Unit Test Report</a></li>
            <li><a href="reports/frontend/integration-tests/index.html">Frontend Integration Test Report</a></li>
            <li><a href="reports/backend/unit-tests/index.html">Backend Unit Test Report</a></li>
            <li><a href="reports/backend/integration-tests/index.html">Backend Integration Test Report</a></li>
            <li><a href="reports/e2e-tests/index.html">E2E Tests Report</a></li>
          </ul>
          EOF

      # Commit and push changes
      - name: Commit and push changes
        if: github.ref == 'refs/heads/develop'
        run: |
          git add .
          git commit -m "Update test reports [skip ci]"
          git push origin gh-pages