deploy-reports:
  name: Deploy Test Reports
  needs: [unit-tests, integration-tests]
  runs-on: ubuntu-latest
  if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}

  steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    # Download artifacts
    - name: Download frontend unit test report
      uses: actions/download-artifact@v3
      with:
        name: frontend-unit-test-report
        path: unit-tests/frontend

    - name: Download backend unit test report
      uses: actions/download-artifact@v3
      with:
        name: backend-unit-test-report
        path: unit-tests/backend

    - name: Download frontend integration test report
      uses: actions/download-artifact@v3
      with:
        name: frontend-integration-test-report
        path: integration-tests/frontend

    - name: Download backend integration test report
      uses: actions/download-artifact@v3
      with:
        name: backend-integration-test-report
        path: integration-tests/backend

    # Debug steps to verify files
    - name: List files in unit-tests/frontend
      run: ls -lR unit-tests/frontend

    - name: List files in unit-tests/backend
      run: ls -lR unit-tests/backend

    - name: List files in integration-tests/frontend
      run: ls -lR integration-tests/frontend

    - name: List files in integration-tests/backend
      run: ls -lR integration-tests/backend

    - name: Commit and push changes
      run: |
        git add unit-tests integration-tests
        git commit -m "Update test reports [skip ci]"
        git push origin gh-pages
