name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  # Unit Tests
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Frontend Unit Tests
      - name: Install dependencies for frontend
        run: npm ci
        working-directory: ./frontend

      - name: Run frontend unit tests and collect coverage
        run: npm run test:ci:unit
        working-directory: ./frontend

      # Backend Unit Tests
      - name: Install dependencies for backend
        run: npm ci
        working-directory: ./backend

      - name: Run backend unit tests and collect coverage
        run: npm run test:ci:unit
        working-directory: ./backend

      # Upload coverage to Coveralls
      - name: Upload unit test coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true

  # Integration Tests
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Frontend Integration Tests
      - name: Install dependencies for frontend
        run: npm ci
        working-directory: ./frontend

      - name: Run frontend integration tests and collect coverage
        run: npm run test:ci:integration
        working-directory: ./frontend

      # Backend Integration Tests
      - name: Install dependencies for backend
        run: npm ci
        working-directory: ./backend

      - name: Run backend integration tests and collect coverage
        run: npm run test:ci:integration
        working-directory: ./backend

      # Upload coverage to Coveralls
      - name: Upload integration test coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true

  # Finalize Coveralls build
  finalize-coveralls:
    name: Finalize Coveralls Coverage
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Finalize Coveralls build
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
