name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  # Unit Tests
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Frontend Unit Tests
      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend unit tests and collect coverage
        working-directory: ./frontend
        run: npm run test:ci:unit

      # Save frontend unit test report
      - name: Upload frontend unit test report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-unit-test-report
          path: ./frontend/coverage/**

      # Backend Unit Tests
      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm ci

      - name: Run backend unit tests and collect coverage
        working-directory: ./backend
        run: npm run test:ci:unit

      # Save backend unit test report
      - name: Upload backend unit test report
        uses: actions/upload-artifact@v3
        with:
          name: backend-unit-test-report
          path: ./backend/coverage/**

  # Integration Tests
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: [unit-tests]
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Frontend Integration Tests
      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend integration tests and collect coverage
        working-directory: ./frontend
        run: npm run test:ci:integration -- --passWithNoTests

      # Save frontend integration test report
      - name: Upload frontend integration test report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-integration-test-report
          path: ./frontend/coverage/**

      # Backend Integration Tests
      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm ci

      - name: Run backend integration tests and collect coverage
        working-directory: ./backend
        run: npm run test:ci:integration

      # Save backend integration test report
      - name: Upload backend integration test report
        uses: actions/upload-artifact@v3
        with:
          name: backend-integration-test-report
          path: ./backend/coverage/**

  # E2E Tests
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: [integration-tests]
    timeout-minutes: 60
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests and generate HTML report
        run: npx playwright test --reporter=html

      # Upload Playwright report as artifact
      - name: Upload Playwright report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/**

  # Deploy Test Reports to GitHub Pages
  deploy-reports:
    name: Deploy Test Reports
    needs: [unit-tests, integration-tests, e2e-tests]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0
          clean: false

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Download artifacts
      - name: Download Playwright report
        uses: actions/download-artifact@v3
        with:
          name: ./frontend/playwright-report
          path: e2e-tests

      - name: Download frontend unit test report
        uses: actions/download-artifact@v3
        with:
          name: frontend-unit-test-report
          path: unit-tests/frontend

      - name: Download backend unit test report
        uses: actions/download-artifact@v3
        with:
          name: backend-unit-test-report
          path: unit-tests/backend

      - name: Download frontend integration test report
        uses: actions/download-artifact@v3
        with:
          name: frontend-integration-test-report
          path: integration-tests/frontend

      - name: Download backend integration test report
        uses: actions/download-artifact@v3
        with:
          name: backend-integration-test-report
          path: integration-tests/backend

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git add unit-tests integration-tests e2e-tests
          git commit -m "Update test reports [skip ci]"
          git push origin gh-pages
