name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  # Unit Tests
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Frontend Unit Tests
      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend unit tests and collect coverage
        working-directory: ./frontend
        run: npm run test:ci:unit

      # Save frontend unit test report
      - name: Upload frontend unit test report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-unit-test-report
          path: ./frontend/coverage/lcov-report/**

      # Backend Unit Tests
      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm ci

      - name: Run backend unit tests and collect coverage
        working-directory: ./backend
        run: npm run test:ci:unit

      # Save backend unit test report
      - name: Upload backend unit test report
        uses: actions/upload-artifact@v3
        with:
          name: backend-unit-test-report
          path: ./backend/coverage/lcov-report/**

  # Integration Tests
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: [unit-tests]
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Frontend Integration Tests
      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend integration tests and collect coverage
        working-directory: ./frontend
        run: npm run test:ci:integration -- --passWithNoTests

      # Save frontend integration test report
      - name: Upload frontend integration test report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-integration-test-report
          path: ./frontend/coverage/lcov-report/**

      # Backend Integration Tests
      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm ci

      - name: Run backend integration tests and collect coverage
        working-directory: ./backend
        run: npm run test:ci:integration

      # Save backend integration test report
      - name: Upload backend integration test report
        uses: actions/upload-artifact@v3
        with:
          name: backend-integration-test-report
          path: ./backend/coverage/lcov-report/**

  # E2E Tests
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: [integration-tests]
    timeout-minutes: 60
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests and generate HTML report
        run: npx playwright test --reporter=html

      - name: List Playwright report files
        run: ls -lR playwright-report

      # Upload Playwright report as artifact
      - name: Upload Playwright report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ./frontend/playwright-report/


  # Deploy Test Reports to GitHub Pages
  deploy-reports:
    name: Deploy Test Reports
    needs: [unit-tests, integration-tests, e2e-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0
          clean: false

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Copy your updated index.html and custom.css from develop branch
      - name: Copy updated index.html and custom.css
        run: |
          git checkout origin/develop -- index.html custom.css workflow_templates/navbar.html
          cp index.html ./
          cp custom.css ./
          cp workflow_templates/navbar.html ./

      # Adjust index.html paths if necessary
      - name: Adjust index.html paths
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)

          # Adjust the CSS link in index.html
          sed -i "s|<link rel=\"stylesheet\" href=\"custom.css\">|<link rel=\"stylesheet\" href=\"/$REPO_NAME/custom.css\">|" index.html

          # Adjust the navbar links in index.html if necessary
          sed -i "s|href=\"index.html\"|href=\"/$REPO_NAME/index.html\"|g; s|href=\"reports/|href=\"/$REPO_NAME/reports/|g" index.html

      # Download artifacts
      - name: Download Playwright report
        uses: actions/download-artifact@v3
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/

      - name: Download frontend unit test report
        uses: actions/download-artifact@v3
        with:
          name: frontend-unit-test-report
          path: unit-tests/frontend

      - name: Download backend unit test report
        uses: actions/download-artifact@v3
        with:
          name: backend-unit-test-report
          path: unit-tests/backend

      - name: Download frontend integration test report
        uses: actions/download-artifact@v3
        with:
          name: frontend-integration-test-report
          path: integration-tests/frontend

      - name: Download backend integration test report
        uses: actions/download-artifact@v3
        with:
          name: backend-integration-test-report
          path: integration-tests/backend

      # Organize Test Reports
      - name: Organize Test Reports
        run: |
          # Remove existing reports directories if they exist
          rm -rf reports/frontend/unit-tests
          rm -rf reports/frontend/integration-tests
          rm -rf reports/backend/unit-tests
          rm -rf reports/backend/integration-tests
          rm -rf reports/e2e-tests

          # Create fresh directories
          mkdir -p reports/frontend/unit-tests
          mkdir -p reports/frontend/integration-tests
          mkdir -p reports/backend/unit-tests
          mkdir -p reports/backend/integration-tests
          mkdir -p reports/e2e-tests

          # Move the reports
          mv unit-tests/frontend/* reports/frontend/unit-tests/
          mv integration-tests/frontend/* reports/frontend/integration-tests/
          mv unit-tests/backend/* reports/backend/unit-tests/
          mv integration-tests/backend/* reports/backend/integration-tests/
          mv e2e-tests/playwright-report/* reports/e2e-tests/

      # Inject Navbar and Custom CSS into Reports (Exclude index.html)
      - name: Inject Navbar and Custom CSS into Reports
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)

          # Inject navbar and custom CSS into all HTML files in reports/
          find reports/ -name '*.html' | while read html_file; do
            # Insert the custom CSS link after the <head> tag
            sed -i "/<head>/a <link rel=\"stylesheet\" href=\"/$REPO_NAME/custom.css\">" "$html_file"

            # Insert the navbar after the <body> tag
            sed -i '/<body>/a <!-- Navbar Start -->' "$html_file"

            # Adjust the navbar links for the reports
            sed "s|href=\"index.html\"|href=\"/$REPO_NAME/index.html\"|g; s|href=\"reports/|href=\"/$REPO_NAME/reports/|g" navbar.html > temp_navbar.html

            # Inject the adjusted navbar
            sed -i '/<!-- Navbar Start -->/r temp_navbar.html' "$html_file"
            sed -i '/<!-- Navbar Start -->/d' "$html_file"

            # Clean up temporary navbar
            rm temp_navbar.html
          done

      # List reports directory to verify
      - name: List reports directory to verify
        run: ls -lR reports/

      # Commit and push changes
      - name: Commit and push changes
        if: github.ref == 'refs/heads/develop'
        run: |
          git add .
          git commit -m "Update test reports [skip ci]"
          git push origin gh-pages
